// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivjivudrwgkixtcrdrzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2aml2dWRyd2draXh0Y3JkcnpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzMzNzMsImV4cCI6MjA2OTEwOTM3M30.dtTkQnfpCbbgzN0tElpvdC_E9IP3IdEwxHeqr_HLxjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});